version: '1.0.0'

services:
  redis:
    container_name: redis_container
    image: redis
    ports:
      - 6379:6379
    command: redis-server --requirepass IEPdpzFxQLHCe4V6rguh5K7bD9AGvXTJ
    restart: always
    volumes: 
      - ./redis:/data
    networks:
      - coderschool-network

  mongodb-primary:
    container_name: mongodb-secondary
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/primary:/data/db
    command: mongod --replSet "rs0"
    environment:
      - MONGO_INITDB_REPLICASET=rs0
    restart: always
    networks:
      - coderschool-network

  mongodb-secondary-1:
    container_name: mongodb-secondary-1
    image: mongo:4.4
    ports:
      - 27018:27017
    volumes:
      - ./mongodb/secondary1:/data/db
    command: mongod --replSet "rs0"
    environment:
      - MONGO_INITDB_REPLICASET=rs0
    restart: always
    networks:
      - coderschool-network

  mongodb-secondary-2:
    container_name: mongodb-secondary-2
    image: mongo:4.4
    ports:
      - 27019:27017
    volumes:
      - ./mongodb/secondary2:/data/db
    command: mongod --replSet "rs0"
    environment:
      - MONGO_INITDB_REPLICASET=rs0
    restart: always
    networks:
      - coderschool-network

  coderschool-server:
    build: .
    ports:
      - 1999:1999
    restart: always
    environment:
      env_file: .env
    depends_on:
      - redis
      - mongodb-primary
      - mongodb-secondary-1
      - mongodb-secondary-2
    networks:
      - coderschool-network

volumes:
  redis:
  mongodb-primary:
  mongodb-secondary-1:
  mongodb-secondary-2:
networks:
  coderschool-network:
    driver: bridge