version: '1.0.0'

services:
  redis:
    container_name: redis_container
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass IEPdpzFxQLHCe4V6rguh5K7bD9AGvXTJ
    volumes: 
      - ./redis:/data

  coderschool-server:
    build: .
    ports:
      - 1999:1999
    restart: always
    environment:
      - PORT=1999
      - HOST=localhost
      - CONSOLE_LOG_LEVEL=OFF
      - FILE_LOG_LEVEL=TRACE
      - LOG_RESPONSE_ENV=default
      - LOG_ERROR_ENV=file
    networks:
      - postgres_network
    depends_on:
      - redis
      - postgres

networks:
  postgres_network:
    driver: bridge

volumes:
  redis: