export enum ErrorCode {
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  INCORRECT_EMAIL_OR_PASSWORD = "INCORRECT_EMAIL_OR_PASSWORD",
  USER_NOT_FOUND = "USER_NOT_FOUND",

  BAD_REQUEST = "BAD_REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",

  POST_NOT_FOUND = "POST_NOT_FOUND",
  REPLY_COMMENT_NOT_FOUND = "REPLY_COMMENT_NOT_FOUND",
  COMMENT_NOT_FOUND = "COMMENT_NOT_FOUND",
}
